language: node_js
node_js:
  - '12.14.1'
cache:
directories:
  - node_modules
services:
  - postgresql
env:
  - NODE_ENV=test PORT=3001 JWT_SECRET=secret DB_USER_TEST=postgres DB_PASSWORD_TEST=postgres DB_NAME_TEST=JetBaseTest DB_HOST_TEST=127.0.0.1
before_script:
  - npm install
  - psql -c 'create database JetBaseTest;' -U postgres
  - npm run migrate
  - npm run seeds-test
script:
  - npm run lint
  - npm run test
